<?php

declare(strict_types=1);

namespace Mindum\Laravel\Tools;

use Illuminate\Contracts\Support\Arrayable;
use Laravel\Mcp\Request;
use Laravel\Mcp\Response;
use Laravel\Mcp\Server\Tool as BaseTool;
use Throwable;

/**
 * Abstract base for tools generated by mindum/laravel.
 *
 * Sits between Laravel\Mcp\Server\Tool and the concrete tool classes the
 * SDK writes to app/Mindum/Tools/. Centralizes:
 *   - Argument extraction (MCP Request → plain array for execute()).
 *   - Result wrapping (turning mixed PHP return values into an MCP Response).
 *   - Exception → error-Response conversion so the agent sees a clean error
 *     result rather than a 500 from the MCP server.
 *
 * Generated tools override execute(array $input) with the handle_code
 * returned by the Mindum API. They never call handle() directly.
 *
 * Targets the laravel/mcp 0.5+ tool contract: handle(Request): Response and
 * schema(JsonSchema): array (the latter emitted by ToolClassRenderer).
 */
abstract class GeneratedTool extends BaseTool
{
    /**
     * The actual business logic from the manifest. Generated tools fill
     * this in with the handle_code returned by the analyze endpoint.
     *
     * @param  array<string, mixed>  $input
     */
    abstract protected function execute(array $input): mixed;

    /**
     * MCP-protocol entry point. Always returns a Response — never throws — so a
     * tool error surfaces as an isError result rather than a 500.
     */
    public function handle(Request $request): Response
    {
        try {
            $result = $this->execute($request->all());
        } catch (Throwable $e) {
            return Response::error($this->formatException($e));
        }

        return $this->wrapResult($result);
    }

    /**
     * Convert a mixed PHP value into an MCP Response the client can render.
     * Arrays / objects / Arrayables are JSON-encoded into a text response (the
     * orchestrator parses the JSON back out); scalars become plain text.
     */
    protected function wrapResult(mixed $value): Response
    {
        if ($value instanceof Response) {
            return $value;
        }

        if ($value === null) {
            return Response::text('null');
        }

        if (is_bool($value)) {
            return Response::text($value ? 'true' : 'false');
        }

        if (is_scalar($value)) {
            return Response::text((string) $value);
        }

        if ($value instanceof Arrayable) {
            $value = $value->toArray();
        }

        if (is_array($value) || is_object($value)) {
            $json = json_encode($value, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

            if ($json !== false) {
                return Response::text($json);
            }

            return Response::text(is_object($value) ? $value::class : '(unrenderable result)');
        }

        return Response::text('(unrenderable result)');
    }

    private function formatException(Throwable $e): string
    {
        return sprintf('%s: %s', class_basename($e), $e->getMessage());
    }
}
