<?php

declare(strict_types=1);

namespace Mindum\Laravel\Tools;

use Illuminate\Contracts\Support\Arrayable;
use Throwable;

/**
 * Abstract base for tools generated by mindum/laravel.
 *
 * Self-sufficient since SDKM-D1 (Docs/SDK_Own_MCP_Plan.md) — no framework
 * MCP package underneath. The SDK's own McpController speaks the wire
 * protocol; this class owns the tool contract:
 *   - name() / description() / inputSchema() feed tools/list.
 *   - handle() runs execute() and wraps the outcome into the MCP result
 *     envelope (`content` blocks + `isError`) — never throws, so a tool
 *     error surfaces as an isError result rather than a 500.
 *
 * Generated tools override execute(array $input) with the handle_code
 * returned by the Mindum API, and inputSchema() with the tool's JSON
 * Schema as a plain array. Pre-SDKM generated files (laravel/mcp-era
 * `schema(JsonSchema)` style) still autoload and execute; their schema
 * degrades to the permissive default below until `mindum:rescan`
 * regenerates them.
 */
abstract class GeneratedTool
{
    public const OPERATION_READ = 'read';

    public const OPERATION_WRITE = 'write';

    public const OPERATION_DELETE = 'delete';

    /** @var list<string> */
    public const OPERATION_TYPES = [self::OPERATION_READ, self::OPERATION_WRITE, self::OPERATION_DELETE];

    abstract public function name(): string;

    abstract public function description(): string;

    /**
     * What this tool does to the customer's data: `read`, `write` or
     * `delete` (CC-D3, Docs/Concierge_Chat_Plan.md). The orchestrator's
     * confirmation gate reads the value `mindum:sync-tools` reports, so a
     * write tool with a read-looking name is still gated.
     *
     * Null means "not declared". Generated tools carry the analyzer's
     * verdict; hand-written tools MUST override this — `mindum:sync-tools`
     * refuses to sync a tool that has not declared it.
     */
    public function operationType(): ?string
    {
        return null;
    }

    /**
     * JSON Schema for the tool's input, as a plain array. Generated tools
     * override this with the schema from the manifest; the default accepts
     * any object so legacy tool files keep working until regenerated.
     *
     * @return array<string, mixed>
     */
    public function inputSchema(): array
    {
        return ['type' => 'object'];
    }

    /**
     * The actual business logic from the manifest. Generated tools fill
     * this in with the handle_code returned by the analyze endpoint.
     *
     * @param  array<string, mixed>  $input
     */
    abstract protected function execute(array $input): mixed;

    /**
     * Protocol entry point, called by McpController for tools/call. Always
     * returns a result envelope — never throws.
     *
     * @param  array<string, mixed>  $input
     * @return array{content: list<array{type: string, text: string}>, isError: bool}
     */
    final public function handle(array $input): array
    {
        try {
            $result = $this->execute($input);
        } catch (Throwable $e) {
            return [
                'content' => [['type' => 'text', 'text' => $this->formatException($e)]],
                'isError' => true,
            ];
        }

        return [
            'content' => [['type' => 'text', 'text' => $this->stringifyResult($result)]],
            'isError' => false,
        ];
    }

    /**
     * Convert a mixed PHP value into the text the orchestrator renders.
     * Arrays / objects / Arrayables are JSON-encoded (the orchestrator
     * parses the JSON back out); scalars become plain text. Same semantics
     * as the laravel/mcp-era wrapResult, minus the Response objects.
     */
    protected function stringifyResult(mixed $value): string
    {
        if ($value === null) {
            return 'null';
        }

        if (is_bool($value)) {
            return $value ? 'true' : 'false';
        }

        if (is_scalar($value)) {
            return (string) $value;
        }

        if ($value instanceof Arrayable) {
            $value = $value->toArray();
        }

        if (is_array($value) || is_object($value)) {
            $json = json_encode($value, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

            if ($json !== false) {
                return $json;
            }

            return is_object($value) ? $value::class : '(unrenderable result)';
        }

        return '(unrenderable result)';
    }

    private function formatException(Throwable $e): string
    {
        return sprintf('%s: %s', class_basename($e), $e->getMessage());
    }
}
