<?php

declare(strict_types=1);

namespace Mindum\Laravel\Tools;

use Illuminate\Contracts\Support\Arrayable;
use Laravel\Mcp\Server\Tool as BaseTool;
use Laravel\Mcp\Server\Tools\ToolResult;
use Throwable;

/**
 * Abstract base for tools generated by mindum/laravel.
 *
 * Sits between Laravel\Mcp\Server\Tool and the concrete tool classes the
 * SDK writes to app/Mindum/Tools/. Centralizes:
 *   - Result wrapping (turning mixed PHP return values into ToolResult).
 *   - Exception → ToolResult::error conversion so the agent sees a clean
 *     error rather than a 500.
 *
 * Generated tools override execute(array $input) with the handle_code
 * returned by the Mindum API. They never call handle() directly.
 */
abstract class GeneratedTool extends BaseTool
{
    /**
     * The actual business logic from the manifest. Generated tools fill
     * this in with the handle_code returned by the analyze endpoint.
     *
     * @param  array<string, mixed>  $input
     */
    abstract protected function execute(array $input): mixed;

    /**
     * MCP-protocol entry point. Always returns a ToolResult — never throws.
     *
     * @param  array<string, mixed>  $arguments
     */
    public function handle(array $arguments): ToolResult
    {
        try {
            $result = $this->execute($arguments);
        } catch (Throwable $e) {
            return ToolResult::error($this->formatException($e));
        }

        return $this->wrapResult($result);
    }

    /**
     * Convert a mixed PHP value into a ToolResult the MCP client can render.
     */
    protected function wrapResult(mixed $value): ToolResult
    {
        if ($value instanceof ToolResult) {
            return $value;
        }

        if ($value === null) {
            return ToolResult::text('null');
        }

        if (is_bool($value)) {
            return ToolResult::text($value ? 'true' : 'false');
        }

        if (is_scalar($value)) {
            return ToolResult::text((string) $value);
        }

        if ($value instanceof Arrayable) {
            return ToolResult::json($value->toArray());
        }

        if (is_array($value)) {
            return ToolResult::json($value);
        }

        if (is_object($value)) {
            $encoded = json_encode($value);
            $decoded = $encoded !== false ? json_decode($encoded, true) : null;

            return is_array($decoded)
                ? ToolResult::json($decoded)
                : ToolResult::text((string) get_class($value));
        }

        return ToolResult::text('(unrenderable result)');
    }

    private function formatException(Throwable $e): string
    {
        return sprintf('%s: %s', class_basename($e), $e->getMessage());
    }
}
