<?php

declare(strict_types=1);

namespace Mindum\Laravel\Tools;

use InvalidArgumentException;

/**
 * Pure function: takes one tool definition (as returned by the Mindum API)
 * and renders it to PHP source code for a concrete tool class.
 *
 * The first line of every emitted file is the literal marker
 * `// @mindum-generated`. ToolWriter uses this marker to identify
 * SDK-owned files during rescan orphan cleanup (Option B header marker).
 *
 * Generated classes extend Mindum\Laravel\Tools\GeneratedTool which in
 * turn extends Laravel\Mcp\Server\Tool. The intermediate GeneratedTool
 * provides result-wrapping (PHP mixed → ToolResult) so handle_code
 * snippets can just `return` whatever they want.
 */
class ToolClassRenderer
{
    public const MARKER = '// @mindum-generated';

    public function __construct(
        private readonly string $namespace = 'App\\Mindum\\Tools',
    ) {}

    /**
     * @param  array<string, mixed>  $tool  Tool definition from /api/analyze.
     * @return array{class_name: string, file_name: string, source: string}
     */
    public function render(array $tool): array
    {
        $toolName = (string) ($tool['name'] ?? '');
        if ($toolName === '') {
            throw new InvalidArgumentException('Tool definition missing "name"');
        }

        $description = (string) ($tool['description'] ?? '');
        $handleCode = trim((string) ($tool['handle_code'] ?? 'return null;'));
        $inputSchema = is_array($tool['input_schema'] ?? null) ? $tool['input_schema'] : [];
        $sourceClass = isset($tool['source_class']) ? (string) $tool['source_class'] : null;
        $operationType = isset($tool['operation_type']) ? (string) $tool['operation_type'] : null;
        $defaultEnabled = $tool['default_enabled'] ?? null;

        $className = $this->classNameFromToolName($toolName);
        $fileName = "{$className}.php";

        $schemaBody = $this->renderSchemaBody($inputSchema);
        $handleBody = $this->indentHandleCode($handleCode);
        $descriptionLiteral = $this->phpStringLiteral($description);
        $nameLiteral = $this->phpStringLiteral($toolName);

        $provenanceLines = [];
        if ($sourceClass !== null) {
            $provenanceLines[] = '// Source class: '.$sourceClass;
        }
        if ($operationType !== null) {
            $provenanceLines[] = '// Operation type: '.$operationType;
        }
        if ($defaultEnabled !== null) {
            $provenanceLines[] = '// Default enabled: '.($defaultEnabled ? 'true' : 'false');
        }
        $provenance = $provenanceLines === [] ? '' : "\n".implode("\n", $provenanceLines);

        $marker = self::MARKER;
        $namespace = $this->namespace;

        $source = <<<PHP
<?php

{$marker}
//
// This file was generated by mindum/laravel from your codebase.
// Do not edit by hand — your changes will be lost on the next rescan.
// Run `php artisan mindum:rescan` to regenerate.{$provenance}

declare(strict_types=1);

namespace {$namespace};

use Laravel\\Mcp\\Server\\Tools\\ToolInputSchema;
use Mindum\\Laravel\\Tools\\GeneratedTool;

class {$className} extends GeneratedTool
{
    public function name(): string
    {
        return {$nameLiteral};
    }

    public function description(): string
    {
        return {$descriptionLiteral};
    }

    public function schema(ToolInputSchema \$schema): ToolInputSchema
    {
{$schemaBody}
        return \$schema;
    }

    /**
     * @param array<string, mixed> \$input
     */
    protected function execute(array \$input): mixed
    {
{$handleBody}
    }
}

PHP;

        return [
            'class_name' => $className,
            'file_name' => $fileName,
            'source' => $source,
        ];
    }

    /**
     * snake_case tool name → PascalCase class name. Stripping invalid chars.
     */
    public function classNameFromToolName(string $toolName): string
    {
        $cleaned = preg_replace('/[^A-Za-z0-9_]+/', '_', $toolName) ?? $toolName;
        $parts = array_filter(explode('_', $cleaned), static fn (string $p) => $p !== '');
        $studly = implode('', array_map(static fn (string $p) => ucfirst(strtolower($p)), $parts));

        if ($studly === '' || preg_match('/^[A-Za-z]/', $studly) !== 1) {
            $studly = 'Tool'.$studly;
        }

        return $studly;
    }

    /**
     * Render the body of schema() using ToolInputSchema::raw() per property.
     * Required fields call ->required() to register with the schema.
     *
     * @param  array<string, mixed>  $inputSchema
     */
    private function renderSchemaBody(array $inputSchema): string
    {
        $properties = is_array($inputSchema['properties'] ?? null) ? $inputSchema['properties'] : [];
        $required = is_array($inputSchema['required'] ?? null) ? $inputSchema['required'] : [];

        if ($properties === []) {
            return '        // No input fields.';
        }

        $lines = [];
        foreach ($properties as $name => $schema) {
            $name = (string) $name;
            $schemaExport = $this->exportArrayInline(is_array($schema) ? $schema : []);
            $isRequired = in_array($name, $required, true);

            $nameLiteral = $this->phpStringLiteral($name);
            $call = "        \$schema->raw({$nameLiteral}, {$schemaExport})";
            if ($isRequired) {
                $call .= '->required()';
            }
            $call .= ';';
            $lines[] = $call;
        }

        return implode("\n", $lines);
    }

    /**
     * Inline-export an array using var_export but compress whitespace so it
     * fits on a single line (or two) in the generated source.
     *
     * @param  array<string, mixed>  $value
     */
    private function exportArrayInline(array $value): string
    {
        $exported = var_export($value, true);
        // var_export emits "array (\n  'k' => 'v',\n)" — collapse to short syntax
        // and trim trailing commas before closing brackets.
        $exported = preg_replace('/\s+/', ' ', $exported) ?? $exported;
        $exported = str_replace(['array (', ')'], ['[', ']'], $exported);
        $exported = preg_replace('/, ]/', ']', $exported) ?? $exported;

        return $exported;
    }

    /**
     * Indent each non-empty line of the handle code by 8 spaces so it sits
     * correctly inside the execute() method body.
     */
    private function indentHandleCode(string $code): string
    {
        $lines = preg_split('/\r\n|\r|\n/', $code) ?: [$code];
        $indented = array_map(
            static fn (string $line) => $line === '' ? '' : '        '.$line,
            $lines,
        );

        return implode("\n", $indented);
    }

    /**
     * Convert any string to a PHP single-quoted literal safely. var_export
     * handles all escaping (newlines, embedded quotes, unicode).
     */
    private function phpStringLiteral(string $value): string
    {
        return var_export($value, true);
    }
}
