<?php

declare(strict_types=1);

namespace Mindum\Laravel\Tools;

use InvalidArgumentException;

/**
 * Pure function: takes one tool definition (as returned by the Mindum API)
 * and renders it to PHP source code for a concrete tool class.
 *
 * The first line of every emitted file is the literal marker
 * `// @mindum-generated`. ToolWriter uses this marker to identify
 * SDK-owned files during rescan orphan cleanup (Option B header marker).
 *
 * Generated classes extend Mindum\Laravel\Tools\GeneratedTool — the SDK's
 * own, framework-free tool base (SDKM-D2: emitted code must run on
 * Laravel 9 / PHP 8.1, so no Illuminate JsonSchema contract and no
 * builder chains; the input schema is embedded as a plain PHP array).
 * GeneratedTool provides result-wrapping so handle_code snippets can
 * just `return` whatever they want.
 */
class ToolClassRenderer
{
    public const MARKER = '// @mindum-generated';

    public function __construct(
        private readonly string $namespace = 'App\\Mindum\\Tools',
    ) {}

    /**
     * @param  array<string, mixed>  $tool  Tool definition from /api/analyze.
     * @return array{class_name: string, file_name: string, source: string}
     */
    public function render(array $tool): array
    {
        $toolName = (string) ($tool['name'] ?? '');
        if ($toolName === '') {
            throw new InvalidArgumentException('Tool definition missing "name"');
        }

        $description = (string) ($tool['description'] ?? '');
        $handleCode = trim((string) ($tool['handle_code'] ?? 'return null;'));
        $inputSchema = is_array($tool['input_schema'] ?? null) ? $tool['input_schema'] : [];
        $sourceClass = isset($tool['source_class']) ? (string) $tool['source_class'] : null;
        $operationType = isset($tool['operation_type']) ? (string) $tool['operation_type'] : null;
        $defaultEnabled = $tool['default_enabled'] ?? null;

        $className = $this->classNameFromToolName($toolName);
        $fileName = "{$className}.php";

        $schemaBody = $this->renderSchemaBody($inputSchema);
        $handleBody = $this->indentHandleCode($handleCode);
        $descriptionLiteral = $this->phpStringLiteral($description);
        $nameLiteral = $this->phpStringLiteral($toolName);

        $provenanceLines = [];
        if ($sourceClass !== null) {
            $provenanceLines[] = '// Source class: '.$sourceClass;
        }
        if ($operationType !== null) {
            $provenanceLines[] = '// Operation type: '.$operationType;
        }
        if ($defaultEnabled !== null) {
            $provenanceLines[] = '// Default enabled: '.($defaultEnabled ? 'true' : 'false');
        }
        $provenance = $provenanceLines === [] ? '' : "\n".implode("\n", $provenanceLines);

        $marker = self::MARKER;
        $namespace = $this->namespace;

        $source = <<<PHP
<?php

{$marker}
//
// This file was generated by mindum/laravel from your codebase.
// Do not edit by hand — your changes will be lost on the next rescan.
// Run `php artisan mindum:rescan` to regenerate.{$provenance}

declare(strict_types=1);

namespace {$namespace};

use Mindum\\Laravel\\Tools\\GeneratedTool;

class {$className} extends GeneratedTool
{
    public function name(): string
    {
        return {$nameLiteral};
    }

    public function description(): string
    {
        return {$descriptionLiteral};
    }

    /**
     * @return array<string, mixed>
     */
    public function inputSchema(): array
    {
        return {$schemaBody};
    }

    /**
     * @param array<string, mixed> \$input
     */
    protected function execute(array \$input): mixed
    {
{$handleBody}
    }
}

PHP;

        return [
            'class_name' => $className,
            'file_name' => $fileName,
            'source' => $source,
        ];
    }

    /**
     * snake_case tool name → PascalCase class name. Stripping invalid chars.
     */
    public function classNameFromToolName(string $toolName): string
    {
        $cleaned = preg_replace('/[^A-Za-z0-9_]+/', '_', $toolName) ?? $toolName;
        $parts = array_filter(explode('_', $cleaned), static fn (string $p) => $p !== '');
        $studly = implode('', array_map(static fn (string $p) => ucfirst(strtolower($p)), $parts));

        if ($studly === '' || preg_match('/^[A-Za-z]/', $studly) !== 1) {
            $studly = 'Tool'.$studly;
        }

        return $studly;
    }

    /**
     * Render the body of schema() as a map of property-name => JsonSchema
     * builder chain, per laravel/mcp's `schema(JsonSchema $schema): array`
     * API (0.5+/0.7). The lines are emitted at 12-space indent to sit inside
     * the generated `return [ ... ];`.
     *
     * @param  array<string, mixed>  $inputSchema
     */
    /**
     * Render the tool's JSON Schema as a PHP array literal for the
     * generated inputSchema() body (SDKM-D2 — plain arrays, no builder,
     * no Illuminate contracts; the wire format wants the raw schema
     * anyway). Normalizes the top level to `type: object` and keeps only
     * the members the orchestrator forwards to Anthropic.
     *
     * @param  array<string, mixed>  $inputSchema
     */
    private function renderSchemaBody(array $inputSchema): string
    {
        $schema = ['type' => 'object'];

        $properties = is_array($inputSchema['properties'] ?? null) ? $inputSchema['properties'] : [];
        if ($properties !== []) {
            $schema['properties'] = $properties;
        }

        $required = is_array($inputSchema['required'] ?? null) ? array_values($inputSchema['required']) : [];
        if ($required !== []) {
            $schema['required'] = $required;
        }

        return $this->exportArray($schema, 2);
    }

    /**
     * Recursively export a value as short-syntax PHP source, indented to
     * sit inside the generated method at the given depth (4-space units).
     * List arrays drop their numeric keys.
     */
    private function exportArray(mixed $value, int $depth): string
    {
        if (! is_array($value)) {
            return var_export($value, true);
        }

        if ($value === []) {
            return '[]';
        }

        $pad = str_repeat('    ', $depth + 1);
        $closePad = str_repeat('    ', $depth);
        $isList = array_keys($value) === range(0, count($value) - 1);

        $lines = [];
        foreach ($value as $key => $item) {
            $prefix = $isList ? '' : var_export($key, true).' => ';
            $lines[] = $pad.$prefix.$this->exportArray($item, $depth + 1).',';
        }

        return "[\n".implode("\n", $lines)."\n".$closePad.']';
    }

    /**
     * Indent each non-empty line of the handle code by 8 spaces so it sits
     * correctly inside the execute() method body.
     */
    private function indentHandleCode(string $code): string
    {
        $lines = preg_split('/\r\n|\r|\n/', $code) ?: [$code];
        $indented = array_map(
            static fn (string $line) => $line === '' ? '' : '        '.$line,
            $lines,
        );

        return implode("\n", $indented);
    }

    /**
     * Convert any string to a PHP single-quoted literal safely. var_export
     * handles all escaping (newlines, embedded quotes, unicode).
     */
    private function phpStringLiteral(string $value): string
    {
        return var_export($value, true);
    }
}
